/*
 * ProgressDialog.java
 *
 * Created on 02.04.2009, 15:16:57
 */

package ch.fhnw.lernstickwelcome;

import java.awt.Frame;
import javax.swing.Icon;

/**
 * the progress dialog when installing packages
 * @author Ronny Standtke <Ronny.Standtke@gmx.net>
 */
public class ProgressDialog extends javax.swing.JDialog {

    private final Frame parent;

    /** Creates new form ProgressDialog
     * @param parent the parent frame
     * @param topIcon the top icon to show
     */
    public ProgressDialog(Frame parent, Icon topIcon) {
        super(parent, true);
        this.parent = parent;

        initComponents();

        iconLabel.setIcon(topIcon);
        
        pack();
        setLocationRelativeTo(parent);
    }

    /**
     * sets the application that is currently installed
     * @param appInfo
     */
    public void setProgressAction(ProgressAction appInfo) {
        System.out.println("*********setProgressAction*********");
        infoLabel.setIcon(appInfo.getIcon());
        infoLabel.setText(appInfo.getDescription());
    }

    /**
     * shows or hides the progress bar
     * @param visible if <tt>true</tt>, the progress bar is shown, otherwise
     * hidden
     */
    public void setProgressBarVisible(boolean visible) {
        progressBar.setVisible(visible);
        pack();
        setLocationRelativeTo(parent);
    }

    /**
     * updates the installation progress
     * @param progress the installation progress
     */
    public void setProgress(int progress) {
        progressBar.setValue(progress);        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconLabel = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ch/fhnw/lernstickwelcome/Bundle"); // NOI18N
        setTitle(bundle.getString("ProgressDialog.title")); // NOI18N

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ch/fhnw/lernstickwelcome/icons/download_anim.gif"))); // NOI18N

        infoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ch/fhnw/lernstickwelcome/icons/48x48/Adobe_Flash_cs3.png"))); // NOI18N
        infoLabel.setText(bundle.getString("Installing")); // NOI18N

        progressBar.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconLabel)
                .addGap(18, 18, 18)
                .addComponent(infoLabel)
                .addGap(18, 18, 18)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables

}
