/*
 * UpdateErrorDialog.java
 *
 * Created on 27.10.2009, 13:32:21
 */

package ch.fhnw.lernstickwelcome;

import java.awt.Frame;

/**
 * an error dialog when apt-get update failed
 * @author Ronny Standtke <ronny.standtke@fhnw.ch>
 */
public class UpdateErrorDialog extends javax.swing.JDialog {

    private final String aptGetOutput;

    /** Creates new form UpdateErrorDialog
     * @param parent the parent frame
     * @param aptGetOutput the output of apt-get
     */
    public UpdateErrorDialog(Frame parent, String aptGetOutput) {
        super(parent, true);
        this.aptGetOutput = aptGetOutput;
        initComponents();
        setLocationRelativeTo(parent);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateErrorLabel = new javax.swing.JLabel();
        updateErrorDetailsButton = new javax.swing.JButton();
        updateErrorOKButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ch/fhnw/lernstickwelcome/Bundle"); // NOI18N
        setTitle(bundle.getString("Error")); // NOI18N

        updateErrorLabel.setText(bundle.getString("Welcome.updateErrorLabel.text")); // NOI18N

        updateErrorDetailsButton.setText(bundle.getString("Welcome.updateErrorDetailsButton.text")); // NOI18N
        updateErrorDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateErrorDetailsButtonActionPerformed(evt);
            }
        });

        updateErrorOKButton.setText(bundle.getString("Welcome.updateErrorOKButton.text")); // NOI18N
        updateErrorOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateErrorOKButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateErrorDetailsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                        .addComponent(updateErrorOKButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateErrorDetailsButton)
                    .addComponent(updateErrorOKButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateErrorDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateErrorDetailsButtonActionPerformed
        AptGetOutputDialog dialog = new AptGetOutputDialog(this, aptGetOutput);
        dialog.setVisible(true);
}//GEN-LAST:event_updateErrorDetailsButtonActionPerformed

    private void updateErrorOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateErrorOKButtonActionPerformed
        setVisible(false);
        dispose();
}//GEN-LAST:event_updateErrorOKButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton updateErrorDetailsButton;
    private javax.swing.JLabel updateErrorLabel;
    private javax.swing.JButton updateErrorOKButton;
    // End of variables declaration//GEN-END:variables

}
